# Generated by Django 4.1.3 on 2024-01-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todolist_data_alter_todolist_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='data',
            new_name='date',
        ),
    ]
